export const userColumns = [
  { field: "id", headerName: "ID", width: 70 },
  {
    field: "user",
    headerName: "User",
    width: 230,
    renderCell: (params) => {
      return (
        <div className="cellWithImg">
          <img src={params.row.img} alt="avatar" className="cellImg" />
          {params.row.username}
        </div>
      );
    },
  },
  {
    field: "email",
    headerName: "Email",
    width: 230,
  },
  {
    field: "age",
    headerName: "Age",
    width: 100,
  },
  {
    field: "status",
    headerName: "Status",
    width: 160,
    renderCell: (params) => {
      return (
        <div className={`cellWithStatus ${params.row.status}`}>
          {params.row.status}
        </div>
      );
    },
  },
];

// temporary data
export const userRows = [
  {
    id: 1,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "active",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 2,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "passive",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 3,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "pending",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 4,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "active",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 5,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "active",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 6,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "pending",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 7,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "passive",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 8,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "active",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 9,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "pending",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 10,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "passive",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 11,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "passive",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
      id: 12,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "active",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 13,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "passive",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 14,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "pending",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 15,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "active",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 16,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "active",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 17,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "pending",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 18,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "passive",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 19,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "active",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 20,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "pending",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 21,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "passive",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 22,
    username: "Snow",
    img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
    status: "passive",
    email: "1snow@gmail.com",
    age: 35,
  },
      {
        id: 23,
        username: "Snow",
        img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
        status: "active",
        email: "1snow@gmail.com",
        age: 35,
      },
      {
        id: 24,
        username: "Snow",
        img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
        status: "passive",
        email: "1snow@gmail.com",
        age: 35,
      },
      {
        id: 25,
        username: "Snow",
        img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
        status: "pending",
        email: "1snow@gmail.com",
        age: 35,
      },
      {
        id: 26,
        username: "Snow",
        img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
        status: "active",
        email: "1snow@gmail.com",
        age: 35,
      },
      {
        id: 27,
        username: "Snow",
        img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
        status: "active",
        email: "1snow@gmail.com",
        age: 35,
      },
      {
        id: 28,
        username: "Snow",
        img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
        status: "pending",
        email: "1snow@gmail.com",
        age: 35,
      },
      {
        id: 29,
        username: "Snow",
        img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
        status: "passive",
        email: "1snow@gmail.com",
        age: 35,
      },
      {
        id: 30,
        username: "Snow",
        img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
        status: "active",
        email: "1snow@gmail.com",
        age: 35,
      },
      {
        id: 31,
        username: "Snow",
        img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
        status: "pending",
        email: "1snow@gmail.com",
        age: 35,
      },
      {
        id: 32,
        username: "Snow",
        img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
        status: "passive",
        email: "1snow@gmail.com",
        age: 35,
      },
      {
        id: 33,
        username: "Snow",
        img: "https://pluspng.com/img-png/user-png-icon-young-user-icon-2400.png",
        status: "passive",
        email: "1snow@gmail.com",
        age: 35,
      },
];

export const productRows = [
  {
      id: 1,
      product: "Acer Nitro 5",
      img: "https://th.bing.com/th/id/OIP.5EZRHGR0LgL2IWcQ511TkQHaF5?pid=ImgDet&rs=1",
      customer: "John Smith",
      date: "1 March",
      amount: 785,
      method: "Cash on Delivery",
      status: "Approved",
  },
  {
      id: 2,
      product: "Playstation 5",
      img: "https://th.bing.com/th/id/R.77c5e8c365e94522eaca1270c9a13db5?rik=TRBAzoM0BMw8Ig&riu=http%3a%2f%2fvaluenomad.com%2fwp-content%2fuploads%2f2016%2f09%2fbest-budget-dell-laptop.jpg&ehk=qJe3kmRy8Jn%2fe3MtilFmX0c5pCVB2lar0jFFb12kYwo%3d&risl=&pid=ImgRaw&r=0",
      customer: "Michael Doe",
      date: "1 March",
      amount: 900,
      method: "Online Payment",
      status: "Pending",
  },
  {
      id: 3,
      product: "Redragon S101",
      img: "https://th.bing.com/th/id/R.011ec1c7f249e522bcf8262224aa666b?rik=bnm7BmcnpLZvlg&riu=http%3a%2f%2fmspoweruser.com%2fwp-content%2fuploads%2f2016%2f08%2fMicromax-Alpha-Laptop-3.jpg&ehk=ELNqBrOi34RVfpeOX%2bn81Vd7%2fHKyMgSSX3D6DB4WPBg%3d&risl=&pid=ImgRaw&r=0",
      customer: "John Smith",
      date: "1 March",
      amount: 75,
      method: "Cash on Delivery",
      status: "Pending",
  },
  {
      id: 4,
      product: "Razer Blade",
      img: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6405/6405054ld.jpg",
      customer: "Jane Smith",
      date: "1 March",
      amount: 920,
      method: "Online",
      status: "Approved",
  },
  {
      id: 5,
      product: "ASUS ROG Strix",
      img: "https://www.lifewire.com/thmb/02xrHGpkKP0kGp-ioxGJcdYQhrg=/1500x1125/filters:fill(auto,1)/4065134-4-5c315e9a46e0fb0001ca20f2.jpg",
      customer: "Harold Carol",
      date: "1 March",
      amount: 2000,
      method: "Online",
      status: "Pending",
  },
]
